# Settings
AUTHOR = "Ryan Kruse"
STUDENT = "#001099380"
GITHUB = "https://github.com/RyanKruse"
TRUCK_STORAGE_LIMIT = 16
TRUCK_SPEED_PER_MILE = 18
TRUCK_SPEED_PER_SECOND = ((TRUCK_SPEED_PER_MILE / 60) / 60)
INT_MAX = 99999
SEED_COUNT = 30
SIMULATION_START_TIME = "8:00:00"
FLIGHT_DELAY_TIME = "9:05:00"
BAD_ADDRESS_TIME = "10:20:00"
DISTANCE_FILE = 'supporting_files/WGUPS_Distance_Table.csv'
PACKAGE_FILE = 'supporting_files/WGUPS_Package_File.csv'
